name = "cf-work"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "4a595c07-ecf5-4286-8b5d-431dd7b93715"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
